version: "3"
services:
    frontend:
        container_name: awesome_web
        build:
            context: ./
            dockerfile: Dockerfile
        image: bdanzer/awesome_web
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/app
    backend:
        container_name: awesome_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: bdanzer/awesome_server
        ports:
            - "4000:4000"
        volumes:
            - ./server:/usr/src/app
    # certbot:
    #     container_name: certbot
    #     build: ./certbot
    #     restart: always
    #     volumes:
    #       - certbot-webroot-evsoul:/webroots/evsoul.com/.well-known
    #       - certbot-letsencrypt:/etc/letsencrypt